javascripts:
  app:
    - public/javascripts/jquery.min.js
    - public/javascripts/cufon.js
    - public/javascripts/Copper.font.js
    - public/javascripts/jquery.masonry.min.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/jquery_ui.custom.min.js
    - public/javascripts/jquery.oembed.min.js
    - public/javascripts/jquery.tipsy.js
    - public/javascripts/fancybox/jquery.easing-1.3.pack.js
    - public/javascripts/fancybox/jquery.mousewheel-3.0.4.pack.js
    - public/javascripts/fancybox/jquery.fancybox-1.3.4.pack.js
    - public/javascripts/application.js
stylesheets:
  app:
    - public/stylesheets/scaffold.css
    - public/stylesheets/tipsy.css
    - public/stylesheets/layout.css
    - public/javascripts/fancybox/jquery.fancybox-1.3.4.css